//
//  ManagerApprovalViews.swift
//  luxury
//
//  Created by Aditya Chauhan on 15/05/26.
//

import SwiftUI

struct ASTApprovalView: View {
    let ast: AST
    @Environment(\.dismiss) private var dismiss
    @State private var state: ApprovalState = .waiting
    @State private var clientName = "Fetching..."
    @State private var productName = "Fetching..."

    var body: some View {
        ManagerDecisionView(
            title:   "After Sales Ticket",
            heading: "Ticket #\(ast.id.uuidString.prefix(6).uppercased())",
            detail:  "\(clientName) · \(productName)\nGenerated by: \(ast.metadata?.createdBy ?? "Unknown Advisor")\nWarranty: \(ast.warrantyStatus?.capitalized ?? "Unknown")\nNotes: \(ast.description ?? "None")\nRemarks: \(ast.remark ?? "None")",
            photoUrls: ast.metadata?.photos,
            state:   $state,
            dismiss: dismiss
        )
        .onAppear {
            if ast.status.lowercased() == "approved" { state = .approved }
            if ast.status.lowercased() == "rejected" { state = .rejected }
        }
        .task {
            if let clientId = ast.clientId {
                if let client = try? await ClientService().fetchClient(id: clientId) {
                    clientName = client.name
                } else {
                    clientName = "Unknown Client"
                }
            } else {
                clientName = "Unknown Client"
            }
            if let catalog = try? await CatalogService().fetchCatalogs().first(where: { $0.id == ast.productId }) {
                productName = catalog.name
            } else {
                productName = "Unknown Product"
            }
        }
        .onChange(of: state) { _, newValue in
            if newValue == .approved || newValue == .rejected {
                Task {
                    try? await ASTService.shared.updateASTStatus(astId: ast.id, newStatus: newValue.rawValue.lowercased())
                }
            }
        }
    }
}

struct WriteOffApprovalView: View {
    @Environment(\.dismiss) private var dismiss
    @State private var state: ApprovalState = .waiting

    var body: some View {
        ManagerDecisionView(
            title:   "Write-Off Approval",
            heading: "Inventory write-off \(CurrencyManager.shared.symbol)8,20,000",
            detail:  "Cycle Count CC-2026-05 · 3 variance items · Recount completed · Audit trail locked",
            state:   $state,
            dismiss: dismiss
        )
    }
}

struct FullScreenPhoto: Identifiable {
    let id = UUID()
    let url: URL
}

private struct ManagerDecisionView: View {
    let title:   LocalizedStringKey
    let heading: LocalizedStringKey
    let detail:  LocalizedStringKey
    let photoUrls: [String]?
    @Binding var state: ApprovalState
    let dismiss: DismissAction
    
    @State private var selectedPhoto: FullScreenPhoto? = nil

    init(title: LocalizedStringKey, heading: LocalizedStringKey, detail: LocalizedStringKey, photoUrls: [String]? = nil, state: Binding<ApprovalState>, dismiss: DismissAction) {
        self.title = title
        self.heading = heading
        self.detail = detail
        self.photoUrls = photoUrls
        self._state = state
        self.dismiss = dismiss
    }

    var body: some View {
        ZStack {
            AppColors.background.ignoresSafeArea()

            VStack(spacing: 0) {

                ScrollView(showsIndicators: false) {
                    VStack(alignment: .leading, spacing: 18) {
                        StatusBadge(
                            text:   LocalizedStringKey(state.rawValue),
                            status: state == .approved ? .success : state == .rejected ? .error : .pending
                        )

                        VStack(alignment: .leading, spacing: 10) {
                            Text(heading)
                                .font(AppFonts.serif(size: 24, weight: .medium))
                                .foregroundStyle(AppColors.text)
                            Text(detail)
                                .font(AppFonts.sansSerif(size: 13))
                                .foregroundStyle(AppColors.secondary)
                                .lineSpacing(4)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding(16)
                        .background(AppColors.surface)
                        .clipShape(RoundedRectangle(cornerRadius: 12))

                        if let urls = photoUrls, !urls.isEmpty {
                            VStack(alignment: .leading, spacing: 12) {
                                Text("CONDITION PHOTOS")
                                    .font(AppFonts.sansSerif(size: 10, weight: .bold))
                                    .foregroundStyle(AppColors.secondary)
                                    .kerning(1.5)
                                
                                ScrollView(.horizontal, showsIndicators: false) {
                                    HStack(spacing: 12) {
                                        ForEach(urls, id: \.self) { urlString in
                                            if let url = URL(string: urlString) {
                                                Button(action: {
                                                    selectedPhoto = FullScreenPhoto(url: url)
                                                }) {
                                                    AsyncImage(url: url) { phase in
                                                        if let image = phase.image {
                                                            image
                                                                .resizable()
                                                                .scaledToFill()
                                                        } else if phase.error != nil {
                                                            Image(systemName: "exclamationmark.triangle")
                                                                .foregroundStyle(AppColors.error)
                                                        } else {
                                                            ProgressView()
                                                        }
                                                    }
                                                    .frame(width: 120, height: 120)
                                                    .background(AppColors.surface2)
                                                    .clipShape(RoundedRectangle(cornerRadius: 12))
                                                }
                                                .buttonStyle(.plain)
                                            }
                                        }
                                    }
                                }
                            }
                            .padding(16)
                            .background(AppColors.surface)
                            .clipShape(RoundedRectangle(cornerRadius: 12))
                        }


                        HStack(spacing: 12) {
                            CustomOutlineButton(
                                title: "Reject",
                                icon: AnyView(Image(systemName: "xmark.circle")),
                                action: { state = .rejected }
                            )
                            CustomButton(
                                title: "Approve",
                                icon: AnyView(Image(systemName: "checkmark.circle")),
                                action: { state = .approved }
                            )
                        }
                    }
                    .padding(.horizontal, 24)
                    .padding(.vertical, 20)
                }
            }
        }
        .navigationTitle("Details")
        .navigationBarTitleDisplayMode(.inline)
        .toolbarBackground(AppColors.background, for: .navigationBar)
        .toolbarBackground(.visible, for: .navigationBar)
        .toolbarColorScheme(.dark, for: .navigationBar)
        .fullScreenCover(item: $selectedPhoto) { photo in
            ZStack {
                AppColors.background.ignoresSafeArea()
                
                VStack(spacing: 0) {
                    HStack {
                        Spacer()
                        Button(action: {
                            selectedPhoto = nil
                        }) {
                            Image(systemName: "xmark.circle.fill")
                                .font(.system(size: 32))
                                .foregroundStyle(.white.opacity(0.8), .black.opacity(0.4))
                        }
                        .buttonStyle(.plain)
                        .padding(.trailing, 20)
                        .padding(.top, 16)
                        .padding(.bottom, 8)
                    }
                    
                    AsyncImage(url: photo.url) { phase in
                        if let image = phase.image {
                            image
                                .resizable()
                                .scaledToFit()
                        } else if phase.error != nil {
                            VStack(spacing: 12) {
                                Image(systemName: "exclamationmark.triangle")
                                    .font(.system(size: 40))
                                    .foregroundStyle(AppColors.error)
                                Text("Failed to load image")
                                    .font(AppFonts.sansSerif(size: 14))
                                    .foregroundStyle(AppColors.secondary)
                            }
                            .frame(maxWidth: .infinity, maxHeight: .infinity)
                        } else {
                            ProgressView()
                                .scaleEffect(1.5)
                                .tint(.white)
                                .frame(maxWidth: .infinity, maxHeight: .infinity)
                        }
                    }
                    
                    Spacer()
                }
            }
        }
    }
}

#Preview("Write-Off Approval") {
    WriteOffApprovalView()
}
